#!/usr/bin/sh

####################
## BSPWM - Configs
#

pgrep -x sxhkd > /dev/null || sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

# Workspaces
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config window_gap           4
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border color
bspc config focused_border_color '#404040'
bspc config normal_border_color  '#282828'

# Rules
bspc rule -a Gimp desktop='^wrk' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Focus with pointer
bspc config focus_follows_pointer false

# Cursor fix
xsetroot -cursor_name left_ptr &

####################
## Autostart Apps
#

# Wallpapers
nitrogen --restore &

# Compositor
picom --config ~/.config/bspwm/apps/picom/picom.conf &

# Polybar
pkill polybar; polybar -c "$HOME/.config/bspwm/apps/polybar/config.ini" &

# Polkit
lxpolkit

# Notifications
dunst &
