require "core.options"
require "core.keymaps"
require "core.theme"

require "plugins.PLUGINS"
require "plugins.autopairs"
require "plugins.impatient"
require "plugins.treesitter"
require "plugins.indentline"
require "plugins.bufferline"
require "plugins.nvim-tree"
require "plugins.colorizer"
require "plugins.lualine"
require "plugins.alpha"
require "plugins.cmp"
-- require "plugins.lsp"
